apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
spec:
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
    nodePort: 30220
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30221
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: 25672
    nodePort: 30222
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30223
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: rabbitmq
  type: NodePort

# username: user 
# password: HvDxHHJAqRuikn0O